import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
let mode='br',scene,camera,renderer,clock,player,bots=[],keys={},ammo=30,score=0,running=false;
const $=s=>document.querySelector(s);
document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode});
$('#play').onclick=()=>start();onkeydown=e=>keys[e.code]=1;onkeyup=e=>keys[e.code]=0;
function start(){document.querySelector('#menu').classList.add('hidden');document.querySelector('#hud').classList.remove('hidden');running=true;ammo=30;score=0;$('#ammo').textContent=ammo;$('#score').textContent='SCORE 0';$('#modeText').textContent=mode==='br'?'BATTLE ROYALE':'5V5';$('#aliveText').textContent='ALIVE '+(mode==='br'?20:10);init();msg('MATCH STARTED')}
function init(){scene=new THREE.Scene();scene.background=new THREE.Color(0x111827);scene.fog=new THREE.Fog(0x111827,35,170);camera=new THREE.PerspectiveCamera(70,innerWidth/innerHeight,.1,500);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;document.body.appendChild(renderer.domElement);clock=new THREE.Clock();scene.add(new THREE.HemisphereLight(0xd9e8ff,0x263522,2));const sun=new THREE.DirectionalLight(0xffffff,3);sun.position.set(30,60,20);sun.castShadow=true;scene.add(sun);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(240,240),new THREE.MeshStandardMaterial({color:0x26362b,roughness:.9}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
for(let i=0;i<60;i++){const s=1+Math.random()*3,h=1+Math.random()*5,o=new THREE.Mesh(new THREE.BoxGeometry(s,h,s),new THREE.MeshStandardMaterial({color:0x3b4b5c,roughness:.8}));o.position.set((Math.random()-.5)*190,h/2,(Math.random()-.5)*190);o.castShadow=true;scene.add(o)}
player=new THREE.Group();const body=new THREE.Mesh(new THREE.CapsuleGeometry(.45,1.05,6,12),new THREE.MeshStandardMaterial({color:0x2388ff}));body.position.y=1;player.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.36,16,16),new THREE.MeshStandardMaterial({color:0xe1aa83}));head.position.y=1.85;player.add(head);const gun=new THREE.Mesh(new THREE.BoxGeometry(.16,.16,1.2),new THREE.MeshStandardMaterial({color:0x17191f,metalness:.8}));gun.position.set(.45,1.2,-.45);player.add(gun);player.position.set(0,0,12);scene.add(player);
bots=[];const n=mode==='5v5'?9:19;for(let i=0;i<n;i++)spawnBot(i<Math.ceil(n/2));camera.position.set(0,4,19);camera.lookAt(player.position);renderer.domElement.onmousedown=e=>{if(e.button===0)shoot()};onresize=resize;requestAnimationFrame(loop)}
function spawnBot(team){const g=new THREE.Group(),b=new THREE.Mesh(new THREE.CapsuleGeometry(.42,1,5,10),new THREE.MeshStandardMaterial({color:team?0xe84b5d:0xf0c84b}));b.position.y=1;g.add(b);const h=new THREE.Mesh(new THREE.SphereGeometry(.33,12,12),new THREE.MeshStandardMaterial({color:0xc58e70}));h.position.y=1.8;g.add(h);g.position.set((Math.random()-.5)*100,0,(Math.random()-.5)*100);g.userData={alive:true,speed:1.2+Math.random()*1.5};scene.add(g);bots.push(g)}
function shoot(){if(!running||ammo<=0)return;ammo--;$('#ammo').textContent=ammo;const dir=new THREE.Vector3(0,0,-1).applyQuaternion(player.quaternion).normalize(),hits=new THREE.Raycaster(player.position.clone().add(new THREE.Vector3(0,1,0)),dir,0,80).intersectObjects(bots,true);if(hits.length){let g=hits[0].object;while(g.parent&&!g.userData.alive)g=g.parent;if(g.userData.alive){g.userData.alive=false;scene.remove(g);score++;$('#score').textContent='SCORE '+score;msg('ELIMINATION')}}}
function loop(){if(!running)return;const dt=Math.min(clock.getDelta(),.05),x=(keys.KeyD?1:0)-(keys.KeyA?1:0),z=(keys.KeyS?1:0)-(keys.KeyW?1:0);if(x||z){const v=new THREE.Vector3(x,0,z).normalize();player.position.addScaledVector(v,(keys.ShiftLeft?9:5)*dt);player.rotation.y=Math.atan2(v.x,v.z)}player.position.x=THREE.MathUtils.clamp(player.position.x,-110,110);player.position.z=THREE.MathUtils.clamp(player.position.z,-110,110);for(const b of bots)if(b.userData.alive&&b.position.distanceTo(player.position)<35){const d=player.position.clone().sub(b.position).setY(0).normalize();b.position.addScaledVector(d,b.userData.speed*dt);b.lookAt(player.position.x,b.position.y,player.position.z)}camera.position.lerp(new THREE.Vector3(player.position.x,4.2,player.position.z+7),.12);camera.lookAt(player.position.x,1.2,player.position.z-8);renderer.render(scene,camera);requestAnimationFrame(loop)}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}function msg(t){$('#msg').textContent=t;setTimeout(()=>$('#msg').textContent='',1200)}